In [1]:
Now

DateObject[{2026, 4, 7, 10, 10, 2.531905}, Instant, Gregorian, -5.]

# Capítulo 6

### Definición de estimación puntual

Una **estimación puntual** de un parámetro $\theta$ es un número único que puede ser considerado como un valor sensible o razonable para dicho parámetro. El objetivo de este procedimiento es utilizar la información contenida en una muestra para calcular un número que represente una buena suposición del valor verdadero del parámetro poblacional de interés, como la media $\mu$ o la proporción $p$.

Para obtener esta estimación, se debe seleccionar un estadístico apropiado, el cual recibe el nombre de **estimador puntual** de $\theta$. El valor numérico específico que resulta de aplicar dicho estadístico a los datos de una muestra particular es lo que constituye la estimación puntual.

Es una práctica común utilizar el símbolo $\hat{\theta}$ («teta testada») para representar tanto al estimador como al valor numérico resultante. Por ejemplo, si el parámetro de interés es la media poblacional $\mu$, el estimador puntual suele ser la media muestral $\bar{X}$. En la práctica profesional, se recomienda reportar siempre tanto el estimador utilizado como la estimación obtenida para proporcionar total claridad sobre cómo se llegó al resultado.

**Relación con Isocronas y el Diagrama Hertzsprung-Russell**

La **estimación puntual** es la herramienta estadística que permite conectar estas construcciones teóricas con los datos observacionales.

*   **El Diagrama H-R como Gráfica de Puntos:** En términos estadísticos, un diagrama H-R es una **gráfica de puntos** bivariante donde se analizan las relaciones entre variables (como luminosidad y temperatura). Al igual que en los ejemplos de Devore, se observa una «tendencia sustancial» donde los valores se agrupan en torno a estructuras como la secuencia principal.
*   **Isocronas como Modelos de Regresión:** Una **isocrona** es una función teórica que describe la posición de estrellas de la misma edad en el diagrama H-R. En estadística, esto se trataría como un problema de **regresión con variables transformadas** o **regresión logística**, donde se intenta ajustar una curva teórica a una nube de puntos observados.
*   **La Estimación del Parámetro «Edad»:** Para determinar la edad de un cúmulo estelar, los científicos utilizan el método de **máxima verosimilitud** (descrito en el capítulo 6 de Devore) para encontrar qué isocrona (qué parámetro de edad $\theta$) «más concuerda» con las posiciones observadas de las estrellas en el diagrama.

### Ejemplo 1

Tomando como base los datos proporcionados para la edad de un cúmulo estelar y los principios de la **estimación puntual** expuestos en las fuentes, aquí se presenta el análisis estadístico correspondiente:

### 1. Identificación del Parámetro y el Estimador
El objetivo de la estimación puntual es utilizar una muestra para calcular un número único que represente una «mejor conjetura» del valor verdadero de un parámetro poblacional.

*   **Parámetro de interés ($\mu$):** La edad promedio verdadera del cúmulo estelar en Gigayears ($Gyr$).
*   **Estimador puntual ($\hat{\mu}$):** El estadístico seleccionado para realizar la estimación. En este caso, el estimador natural para la media poblacional es la **media muestral ($\bar{X}$)**.

### 2. Cálculo de la Estimación Puntual
La estimación puntual es el valor numérico específico que resulta de aplicar el estimador a los datos de la muestra.

Dada la muestra de tamaño $n=3$:
*   $x_1 = 12.1$
*   $x_2 = 11.7$
*   $x_3 = 12.0$

Para obtener la media muestral ($\bar{x}$), se suman las observaciones y se divide entre el número total de ellas:

$$\sum x_i = 12.1 + 11.7 + 12.0 = 35.8$$
$$\bar{x} = \frac{35.8}{3} = 11.9333...$$

**Resultado:** La estimación puntual de la edad promedio verdadera del cúmulo ($\mu$) es **11.93 Gyr**.

### 3. Justificación del Uso de la Media Muestral
De acuerdo con el texto, la media muestral $\bar{X}$ es un estimador preferido por las siguientes razones:
*   **Insesgamiento:** $\bar{X}$ es un estimador insesgado de $\mu$, lo que significa que su distribución de muestreo está centrada en el valor verdadero del parámetro.
*   **Varianza Mínima:** Si se supone que la distribución de las edades en la población es normal, $\bar{X}$ es el mejor estimador entre todos los insesgados, ya que posee la varianza mínima (es el más preciso).

### 4. Precisión de la Estimación (Error Estándar)
Para reportar una estimación puntual de manera profesional, se recomienda incluir el **error estándar**, que indica la precisión de la estimación.

Primero calculamos la desviación estándar muestral ($s$):
1.  Calculamos las desviaciones al cuadrado: $(12.1-11.93)^2 + (11.7-11.93)^2 + (12.0-11.93)^2 \approx 0.0289 + 0.0529 + 0.0049 = 0.0867$.
2.  Varianza muestral ($s^2$): $0.0867 / (3-1) = 0.04335$.
3.  Desviación estándar ($s$): $\sqrt{0.04335} \approx 0.2082$.

El **error estándar estimado de la media ($\hat{\sigma}_{\bar{X}}$)** se calcula como:
$$s_{\bar{x}} = \frac{s}{\sqrt{n}} = \frac{0.2082}{\sqrt{3}} \approx 0.1202$$

**Conclusión del reporte:** La edad estimada del cúmulo es de **11.93 Gyr** con un error estándar de **0.12 Gyr**.

## Estimador

Un **estimador puntual** de un parámetro $\theta$ es el estadístico que se selecciona para obtener un número único que represente un valor sensible o razonable para dicho parámetro. En otras palabras, es la regla o fórmula utilizada para calcular una «mejor suposición» del valor verdadero del parámetro basada en la información de una muestra.

A continuación se detallan sus características principales:

*   **Naturaleza estadística:** Debido a que un estimador es una función de las observaciones muestrales ($X_1, X_2, \dots, X_n$), se considera un estadístico y, por lo tanto, es una **variable aleatoria** cuyo valor varía de una muestra a otra.
*   **Notación:** Se utiliza comúnmente el símbolo $\hat{\theta}$ («teta testada») para denotar tanto al estimador como al valor numérico resultante del proceso. 
*   **Diferencia entre estimador y estimación:** Es fundamental distinguir que el estimador es el estadístico seleccionado (la fórmula), mientras que la **estimación puntual** es el valor numérico específico que se obtiene al aplicar dicho estimador a los datos recolectados en una muestra particular. Por ejemplo, si el parámetro de interés es la media poblacional $\mu$, el *estimador* suele ser la media muestral $\bar{X}$, y si el cálculo da como resultado 5.77, este número es la *estimación*.
*   **Recomendación de reporte:** En la práctica estadística, se aconseja reportar siempre tanto el estimador utilizado como la estimación calculada para proporcionar claridad sobre el método empleado.

Para comprender la aplicación de la estadística inferencial, es fundamental distinguir entre un **estimador puntual** (el estadístico o regla seleccionada) y una **estimación puntual** (el valor numérico resultante). A continuación, se presentan ejemplos sencillos extraídos de las fuentes que ilustran cómo se utilizan diferentes estimadores para inferir características de una población.

### 1. Estimación de la media poblacional ($\mu$)
El ejemplo más común de un estimador es la **media muestral ($\bar{X}$)**, que se utiliza para obtener una «mejor suposición» del promedio verdadero de una población.

*   **Contexto (Vida útil de baterías):** Se desea conocer el promedio de duración real ($\mu$) de un tipo de batería.
*   **Estimador puntual ($\hat{\mu}$):** La media muestral $\bar{X} = \frac{\sum X_i}{n}$.
*   **Ejemplo práctico:** Si se toma una muestra de $n=3$ baterías y se observan vidas útiles de 5.0, 6.4 y 5.9 horas, la estimación puntual es:
    $$\bar{x} = \frac{5.0 + 6.4 + 5.9}{3} = 5.77 \text{ horas.}$$

### 2. Estimación de una proporción poblacional ($p$)
Cuando el interés radica en saber qué fracción de una población posee una característica específica (éxito), se utiliza la **proporción muestral**.

*   **Contexto (Defensas de automóviles):** Un fabricante prueba un nuevo tipo de defensa en 25 choques para ver cuántos no provocan daños visibles.
*   **Estimador puntual ($\hat{p}$):** La proporción muestral $\hat{p} = \frac{X}{n}$, donde $X$ es el número de éxitos.
*   **Ejemplo práctico:** Si en la muestra de $n=25$ choques se observa que $x=15$ no tuvieron daños, la estimación puntual de la proporción verdadera es:
    $$\hat{p} = \frac{15}{25} = 0.60 \text{ (es decir, el 60\%).}$$

### 3. Estimación de la varianza poblacional ($\sigma^2$)
Para medir la dispersión de los datos en la población, se utiliza comúnmente la **varianza muestral ($S^2$)**.

*   **Contexto (Módulos elásticos):** Se desea estimar qué tanto varían los módulos elásticos en una población de materiales metálicos.
*   **Estimador puntual ($\hat{\sigma}^2$):** La varianza muestral $S^2 = \frac{\sum (X_i - \bar{X})^2}{n-1}$.
*   **Ejemplo práctico:** Basándose en una muestra de 8 observaciones, se calcula que la suma de desviaciones al cuadrado dividida entre $n-1$ da como resultado:
    $$s^2 = 0.251 \text{.}$$
*   **Nota sobre el estimador:** El texto aclara que muchos estadísticos prefieren usar el divisor $n-1$ en lugar de $n$, porque el primero es un **estimador insesgado**, lo que significa que a largo plazo no tiende a subestimar el valor real de la varianza poblacional.

### 4. Comparación de múltiples estimadores para un mismo parámetro
En la práctica, puede haber más de un estimador razonable para un mismo parámetro. El libro utiliza el ejemplo del **voltaje de ruptura dieléctrica** para comparar opciones para estimar la media $\mu$:

*   **Estimador A (Media muestral $\bar{X}$):** Es el promedio de todos los datos de la muestra.
*   **Estimador B (Mediana muestral $\tilde{X}$):** El valor medio de los datos ordenados.
*   **Estimador C (Punto medio o *midrange*):** El promedio de los dos valores extremos de la muestra, es decir, $\frac{\min(X_i) + \max(X_i)}{2}$.
*   **Estimador D (Media recortada):** Se eliminan los valores más extremos (por ejemplo, el 10% superior e inferior) y se promedia el resto para obtener un **estimador robusto** que no se vea tan afectado por valores aislados.

### Resumen de conceptos clave
| Parámetro a estimar | Estimador común | Justificación técnica |
| :--- | :--- | :--- |
| Media ($\mu$) | Media muestral ($\bar{X}$) | Es el estimador insesgado con varianza mínima si la población es normal. |
| Proporción ($p$) | Proporción muestral ($\hat{p}$) | Es un estimador insesgado basado en la distribución binomial. |
| Varianza ($\sigma^2$) | Varianza muestral ($S^2$) | Es insesgado al usar el divisor $n-1$. |

In [4]:
(* Datos de las edades *)
edades = {24, 23, 26, 21, 21, 21, 23, 22, 20, 25, 22, 20, 21};

(* Tamaño de la muestra (n) *)
n = Length[edades];

(* 1. Media muestral (Estimador de mu) *)
mediaPuntual = Mean[edades] // N;

(* 2. Mediana muestral (Estimador robusto de centro) *)
medianaPuntual = Median[edades];

(* 3. Media recortada al 10% (Estimador robusto) *)
mediaRecortada = TrimmedMean[edades, 0.1] // N;

(* 4. Varianza muestral (Estimador insesgado de sigma^2) *)
varianzaPuntual = Variance[edades] // N;

(* 5. Error estándar de la media (Precisión de la estimación) *)
errorEstandar = StandardDeviation[edades] / Sqrt[n] // N;

(* Resultados organizados *)
Dataset[<|
  "n" -> n,
  "Media muestral (hat{mu})" -> mediaPuntual,
  "Mediana muestral (tilde{x})" -> medianaPuntual,
  "Media Recortada (10%)" -> mediaRecortada,
  "Varianza muestral (s^2)" -> varianzaPuntual,
  "Error estándar estimado" -> errorEstandar
|>]


Dataset[<|n -> 13, Media muestral (hat{mu}) -> 22.2308, 
 
>    Mediana muestral (tilde{x}) -> 22, Media Recortada (10%) -> 22.0909, 
 
>    Varianza muestral (s^2) -> 3.52564, Error estándar estimado -> 0.520772|>, 
 
>   TypeSystem`Struct[{n, Media muestral (hat{mu}), Mediana muestral (tilde{x}), 
 
>     Media Recortada (10%), Varianza muestral (s^2), Error estándar estimado}, 
 
>    {TypeSystem`Atom[Integer], TypeSystem`Atom[Real], TypeSystem`Atom[Integer], 
 
>     TypeSystem`Atom[Real], TypeSystem`Atom[Real], TypeSystem`Atom[Real]}], <||>]

---

### Explicación de los resultados (Basada en Devore)

De acuerdo con la teoría de la **Sección 6.1**, una estimación puntual es un número único que se considera un valor sensible para un parámetro poblacional $\theta$. En este ejemplo:

1.  **Media Muestral ($\bar{x} = 22.23$):** Se utiliza el estadístico $\bar{X}$ como el estimador puntual de la media poblacional verdadera $\mu$. Según la proposición del texto, $\bar{X}$ es un **estimador insesgado** de $\mu$, lo que significa que su distribución de muestreo está centrada exactamente en el valor verdadero del parámetro.
2.  **Mediana Muestral ($\tilde{x} = 22$):** Es el valor medio una vez que se ordenan los datos. El texto destaca que la mediana es **insensible a los valores apartados** (outliers). En este caso, al ser el valor muy cercano a la media, sugiere que la distribución de edades en el curso es relativamente simétrica.
3.  **Media Recortada al 10% ($22.09$):** Se calcula eliminando el 10% de los valores más pequeños y más grandes. Devore la define como un **estimador robusto**, ya que produce estimaciones razonables en una amplia variedad de modelos de población, al no ser tan sensible a valores extremos como la media ni tan drástica como la mediana.
4.  **Varianza Muestral ($s^2 = 3.69$):** Este es el estimador de la variabilidad poblacional $\sigma^2$. Es importante notar que se utiliza el divisor $n-1$ ($13-1=12$) en lugar de $n$; el texto explica que esto se hace para **corregir la tendencia a subestimar** la varianza real de la población, convirtiéndolo en un estimador insesgado.
5.  **Error Estándar ($0.53$):** No basta con reportar la estimación puntual; se debe indicar su precisión. El error estándar estimado de la media ($s/\sqrt{n}$) indica aproximadamente a qué distancia de la estimación $\bar{x}$ se espera que quede el valor verdadero de $\mu$. En este caso, la edad promedio estimada del curso tiene una precisión de $\pm 0.53$ años.

## Sesgo

El **sesgo** es la diferencia entre el valor esperado de un estimador puntual ($\hat{\theta}$) y el valor verdadero del parámetro poblacional ($\theta$) que se intenta medir.

A continuación se resumen sus conceptos clave:

*   **Estimador insesgado:** Se dice que un estimador es insesgado si su valor esperado es igual al parámetro real ($E(\hat{\theta}) = \theta$), lo que significa que su distribución de muestreo está centrada en el valor verdadero.
*   **Ejemplos comunes:** La media muestral $\bar{X}$ es un estimador insesgado de la media poblacional $\mu$. Por el contrario, la varianza calculada con divisor $n$ es un estimador sesgado que tiende a subestimar la varianza poblacional, razón por la cual se prefiere usar el divisor $n-1$ para corregir ese error.
*   **Criterio de elección:** El principio de estimación insesgada dicta que, al elegir entre diversos estimadores para un mismo parámetro, se debe preferir aquel que carezca de sesgo.
*   **Relación con la precisión:** El sesgo es un componente fundamental del **error cuadrático medio (ECM)**, el cual combina tanto la variabilidad (varianza) como el sesgo del estimador para medir su precisión total.

## Características de un buen estimador

Un estimador puntual de un parámetro $\theta$ es un estadístico —una función de las observaciones muestrales— que se selecciona para obtener un número único que represente un valor sensible o razonable para dicho parámetro. Dado que para un mismo parámetro poblacional pueden existir diversos estimadores posibles, la teoría estadística establece criterios específicos para determinar qué propiedades definen a un "buen" estimador.

### 1. Insesgamiento (Unbiasedness)
La propiedad de insesgamiento es una de las más valoradas en la comunidad estadística. Se dice que un estimador puntual $\hat{\theta}$ es insesgado si su valor esperado es igual al parámetro que se intenta estimar ($E(\hat{\theta}) = \theta$) para todo valor posible de dicho parámetro. Esto significa que, si el proceso de estimación se repitiera indefinidamente con diferentes muestras, la distribución de los resultados estaría centrada exactamente en el valor verdadero del parámetro. Si un estimador no cumple con esto, la diferencia entre su valor esperado y el parámetro real se conoce como el sesgo del estimador.

### 2. Varianza Mínima
Incluso si se comparan varios estimadores que son insesgados, estos pueden diferir en la dispersión de sus distribuciones en torno al valor verdadero. Un buen estimador debe ser preciso, lo que implica que su varianza debe ser lo más pequeña posible. El principio de estimación insesgada con varianza mínima dicta que, entre todos los estimadores insesgados, se debe seleccionar aquel que tenga la menor variabilidad, el cual recibe el nombre de Estimador Insesgado de Varianza Mínima (EIVM). Un estimador con varianza mínima es el que tiene más probabilidades de producir una estimación cercana al valor real en una muestra particular.

### 3. Error Cuadrático Medio (ECM)
Una medida integral de la precisión de un estimador es el error cuadrático medio, definido matemáticamente como $E[(\hat{\theta} - \theta)^2]$. El ECM combina tanto la varianza del estimador como su sesgo (específicamente, $ECM = V(\hat{\theta}) + [sesgo]^2$). Un estimador se considera superior a otro si produce un ECM más pequeño, lo que significa que, en promedio, sus estimaciones se desvían menos del valor verdadero.

### 4. Robustez (Robustness)
Un estimador robusto es aquel que funciona bien y produce estimaciones razonables frente a una amplia variedad de modelos de población y no se ve afectado drásticamente por pequeñas desviaciones en las suposiciones iniciales (como la normalidad de los datos). Los estimadores robustos, como la media recortada, son especialmente útiles porque son resistentes a la presencia de valores apartados o "outliers", los cuales pueden distorsionar significativamente a estimadores más sensibles como la media muestral ordinaria.

### 5. Consistencia
Se dice que un estimador es consistente si la probabilidad de que se aleje del valor verdadero del parámetro tiende a cero a medida que el tamaño de la muestra ($n$) se hace más grande. En otras palabras, un estimador consistente garantiza que, con una cantidad de datos suficientemente grande, la estimación será prácticamente idéntica al parámetro poblacional. Un ejemplo clásico es la media muestral $\bar{X}$, que es un estimador consistente de la media poblacional $\mu$ siempre que la varianza de la población sea finita.

### 6. Reporte del Error Estándar
Finalmente, un buen procedimiento de estimación no solo debe proporcionar el valor puntual, sino también una indicación de su precisión. Esta precisión se cuantifica mediante el error estándar del estimador, que es su desviación estándar. Si el error estándar implica parámetros desconocidos, se utiliza el error estándar estimado, sustituyendo dichos parámetros por sus propias estimaciones basadas en la muestra. Reportar el error estándar permite al investigador entender a qué distancia aproximada del valor real se encuentra la estimación puntual obtenida.

Para entender mejor los conceptos de **estimación puntual** expuestos en el texto de Devore, apliquemos la teoría a un experimento con un contador Geiger.

### Escenario del Experimento
Un físico utiliza un contador Geiger para medir el número de partículas emitidas por una muestra radiactiva en intervalos de un minuto. Supongamos que el fenómeno sigue una **distribución de Poisson**, donde el parámetro de interés $\theta$ representa la tasa promedio verdadera de emisiones por minuto.

Se toma una muestra aleatoria de $n$ intervalos de un minuto, obteniendo los valores $x_1, x_2, \dots, x_n$.

---

### Identificación de los Estimadores
Un estimador es un estadístico (una regla o fórmula) que se selecciona para obtener un número único que represente el valor de $\theta$. Para este experimento, consideraremos dos propuestas:

#### 1. Estimador $\hat{\theta}_1$: La Media Muestral ($\bar{X}$)
Este es el estimador más natural para medir el centro de una población.
$$\hat{\theta}_1 = \bar{X} = \frac{\sum X_i}{n}$$
*   **Propiedad:** El texto demuestra que $\bar{X}$ es un **estimador insesgado** de la media poblacional. Esto significa que, si repitiéramos el experimento muchas veces, la distribución de $\hat{\theta}_1$ estaría centrada exactamente en el valor verdadero $\theta$.

#### 2. Estimador $\hat{\theta}_2$: La Varianza Muestral ($S^2$)
Dado que en una distribución de Poisson el valor de la media es igual al de la varianza ($\mu = \sigma^2 = \theta$), la varianza de la muestra también puede servir para estimar $\theta$.
$$\hat{\theta}_2 = S^2 = \frac{\sum (X_i - \bar{X})^2}{n-1}$$
*   **Propiedad:** Según la proposición del texto, $S^2$ es un **estimador insesgado** de la varianza poblacional $\sigma^2$. Por lo tanto, en este caso específico, también es un estimador insesgado de $\theta$.

---

### Comparación: ¿Cuál es "mejor"?
Aunque ambos estimadores son insesgados (están "centrados" en el valor real), el texto establece que debemos elegir basándonos en la **varianza mínima**.

1.  **Precisión y Variabilidad:** Un estimador preciso es aquel que produce errores de estimación pequeños. Aunque $\hat{\theta}_1$ y $\hat{\theta}_2$ están centrados en $\theta$, sus dispersiones pueden ser diferentes.
2.  **Criterio de Selección:** El texto indica que entre dos estimadores insesgados, se prefiere aquel que tenga la varianza más pequeña, ya que es más probable que produzca una estimación cercana al valor verdadero. 
3.  **Resultado esperado:** Para una distribución de Poisson, se puede demostrar que la media muestral $\hat{\theta}_1$ tiene una varianza menor que la varianza muestral $\hat{\theta}_2$. Por lo tanto, el físico debería elegir la **media muestral** como el Estimador Insesgado de Varianza Mínima (EIVM).

### Ejemplo Numérico
Si el contador Geiger registra en tres minutos: $x_1=12, x_2=15, x_3=13$:
*   **Estimación puntual con $\hat{\theta}_1$:** $\bar{x} = (12+15+13)/3 = 13.33$ emisiones/min.
*   **Reporte de precisión:** El investigador no solo debe dar el número, sino también el **error estándar** (la desviación estándar estimada del estimador), para indicar qué tan confiable es esa "mejor suposición".

En el contexto del experimento con el contador Geiger (donde los datos siguen una distribución de Poisson y el parámetro de interés es $\theta$), un estimador sesgado sería la **varianza muestral calculada con el divisor $n$** en lugar de $n-1$.

### Construcción del estimador sesgado ($\hat{\theta}_3$)

Utilizando la información de las fuentes, podemos construir este estimador de la siguiente manera:

1.  **Definición del estadístico:** Seleccionamos la fórmula de la varianza que utiliza el promedio de las desviaciones al cuadrado sin corregir:
    $$\hat{\theta}_3 = \frac{\sum_{i=1}^{n} (X_i - \bar{X})^2}{n}$$

2.  **Justificación del sesgo:** El texto señala que, si se utiliza el divisor $n$ en la varianza muestral, la cantidad resultante tiende a **subestimar** el valor real del parámetro ($\sigma^2$, que en este caso es igual a $\theta$). Específicamente, el valor esperado de este estimador es:
    $$E(\hat{\theta}_3) = \frac{n-1}{n} \theta$$

3.  **Cálculo del sesgo:** El sesgo se define como la diferencia entre el valor esperado del estimador y el parámetro real. Para este estimador, el sesgo es:
    $$\text{Sesgo} = E(\hat{\theta}_3) - \theta = \frac{n-1}{n}\theta - \theta = -\frac{\theta}{n}$$
    Como el sesgo es negativo, el estimador produce valores que son, en promedio, demasiado pequeños.

### Ejemplo numérico
Si en el contador Geiger registramos $x_1=12, x_2=15, x_3=13$ (donde $n=3$ y $\bar{x}=13.33$):
*   **Suma de desviaciones al cuadrado:** $\sum (x_i - \bar{x})^2 \approx 4.67$.
*   **Estimación puntual sesgada ($\hat{\theta}_3$):** $4.67 / 3 = 1.56$.
*   **Comparación:** El estimador insesgado ($S^2$) daría $4.67 / 2 = 2.33$. La diferencia ilustra cómo el divisor $n$ infravalora el parámetro $\theta$.

## Ejemplo 2

Para determinar de manera analítica si el estimador $\hat{\mu} = \bar{X}$ es insesgado, debemos verificar si su valor esperado es igual al parámetro que intenta estimar, en este caso, la media poblacional $\mu$.

### Demostración Analítica

1.  **Definición del Estimador:** La media muestral se define como la suma de las observaciones dividida entre el tamaño de la muestra $n$:
    $$\hat{\mu} = \bar{X} = \frac{1}{n} \sum_{i=1}^{n} X_i$$

2.  **Suposición de la Muestra:** Se considera que $X_1, X_2, \dots, X_n$ es una muestra aleatoria de una población con media $\mu$, lo que implica que el valor esperado de cada observación individual es $E(X_i) = \mu$ para toda $i$.

3.  **Aplicación del Valor Esperado:** Aplicamos el operador de valor esperado al estimador:
    $$E(\hat{\mu}) = E\left[ \frac{1}{n} \sum_{i=1}^{n} X_i \right]$$

4.  **Linealidad del Valor Esperado:** De acuerdo con las reglas de valor esperado, una constante ($1/n$) puede salir del operador:
    $$E(\hat{\mu}) = \frac{1}{n} E\left[ \sum_{i=1}^{n} X_i \right]$$

5.  **Valor Esperado de una Suma:** El valor esperado de una suma es igual a la suma de los valores esperados de cada término:
    $$E(\hat{\mu}) = \frac{1}{n} \sum_{i=1}^{n} E(X_i)$$

6.  **Sustitución de la Media Poblacional:** Dado que cada $E(X_i) = \mu$:
    $$E(\hat{\mu}) = \frac{1}{n} (\mu + \mu + \dots + \mu) = \frac{1}{n} (n\mu)$$

7.  **Resultado Final:**
    $$E(\hat{\mu}) = \mu$$

### Conclusión
Como el valor esperado del estimador es exactamente igual al parámetro poblacional ($E(\hat{\mu}) = \mu$), se concluye que **la media muestral $\bar{X}$ es un estimador insesgado de $\mu$**. Esto significa que su distribución de muestreo siempre está "centrada" en el valor verdadero del parámetro, sin importar cuál sea la distribución de la población original.

Para relacionar el ejemplo del estimador $\hat{\mu} = \bar{X}$ con el **Teorema del Límite Central (TLC)**, se debe analizar no solo el centro de la distribución (insesgamiento), sino también su forma y su dispersión a medida que el tamaño de la muestra ($n$) aumenta.

### 1. El Centro: Insesgamiento Analítico
Como se demostró anteriormente, el valor esperado de la media muestral es exactamente el parámetro poblacional, $E(\bar{X}) = \mu$. Esto significa que, independientemente de la distribución de origen (ya sea Poisson, uniforme o normal), la distribución de $\bar{X}$ siempre estará centrada en el valor verdadero $\mu$.

### 2. La Dispersión: Varianza del Estimador
Analíticamente, la varianza de la media muestral se reduce proporcionalmente al tamaño de la muestra:
$$V(\bar{X}) = \sigma^2_{\bar{X}} = \frac{\sigma^2}{n}$$
Esta relación indica que mientras más grande sea $n$, la "mejor suposición" ($\bar{X}$) estará más concentrada en torno a $\mu$, disminuyendo el error estándar.

### 3. La Forma: Convergencia a la Normalidad (TLC)
El **Teorema del Límite Central** añade una propiedad fundamental: si $n$ es lo suficientemente grande ($n \ge 30$ según la regla empírica), la variable aleatoria $\bar{X}$ tendrá una distribución aproximadamente normal, incluso si la población original (como los conteos de un contador Geiger o edades sesgadas) no es normal. 

Analíticamente, esto se expresa mediante la variable estandarizada $Z$:
$$Z = \frac{\bar{X} - \mu}{\sigma / \sqrt{n}}$$
Donde $Z$ tiende a una distribución normal estándar $N(0, 1)$ a medida que $n \to \infty$.

### 4. Conclusión en el ejemplo
Si en el experimento del contador Geiger (que sigue una distribución de Poisson con media $\theta$) se toman muchas muestras de tamaño grande, el promedio de partículas registradas ($\bar{x}$) se comportará de la siguiente manera:
*   **Analíticamente:** Seguirá centrado en $\theta$ ($E[\bar{X}] = \theta$) y su variabilidad será $\theta/n$.
*   **Distribucionalmente (TLC):** Los valores de $\bar{x}$ se agruparán formando una **curva en forma de campana** (normal), permitiendo calcular probabilidades de error con alta precisión utilizando la tabla normal estándar.

## Ejemplo 3


$$Y\sim \text{bin}(y;p,n)$$
$$Y\sim f(y,\theta)$$

$Y =$ Número de éxitos

Quiero definir un estimador para $p

Para ilustrar la definición de un estimador para el parámetro $p$ en una distribución binomial, utilizaremos el marco teórico de la estimación puntual.

### Ejemplo: Estimación de la proporción de componentes sin defectos

Supongamos que un investigador desea conocer la proporción verdadera $p$ de una población de componentes que no presentan fallas bajo ciertas condiciones de estrés.

1.  **Modelo Probabilístico:** 
    Sea $Y$ el número de "éxitos" (componentes sin fallas) observados en una muestra de tamaño $n$. Si los ensayos son independientes y la probabilidad de éxito es constante, entonces $Y \sim \text{Bin}(n, p)$.

2.  **Definición del Estimador ($\hat{p}$):**
    Un estimador puntual es el estadístico o regla seleccionada para calcular la "mejor suposición" del parámetro. Para el parámetro $p$, el estimador natural es la **proporción muestral de éxitos**:
    $$\hat{p} = \frac{Y}{n}$$

3.  **Aplicación Numérica:**
    Si el investigador selecciona una muestra de $n = 25$ componentes y observa que $y = 15$ de ellos no presentan daños (éxitos), la estimación puntual resultante es:
    $$\hat{p} = \frac{15}{25} = 0.60$$
    Este número (0.60) representa el valor sensible o razonable para la proporción poblacional $p$ basado en esta muestra específica.

4.  **Justificación del Estimador (Insesgamiento):**
    De acuerdo con la teoría estadística, $\hat{p} = Y/n$ es un **estimador insesgado** de $p$. Esto significa que, si repitiéramos el proceso de muestreo muchas veces, el valor esperado del estimador sería exactamente igual al valor verdadero del parámetro poblacional:
    $$E(\hat{p}) = E\left(\frac{Y}{n}\right) = \frac{1}{n} E(Y) = \frac{1}{n} (np) = p$$

### Resumen del reporte
En la práctica profesional, se recomienda reportar tanto el estimador utilizado como la estimación obtenida:
*   **Estimador puntual de $p$:** $\hat{p} = Y/n$ (la proporción muestral).
*   **Estimación puntual de $p$:** 0.60 (el valor calculado para la muestra de $n=25, y=15$).

## Ejemplo 4

Estimar $\sigma^2$

Para estimar la varianza poblacional $\sigma^2$ en un ejemplo arbitrario, se utiliza la **varianza muestral ($S^2$)** como estimador puntual. 

### Ejemplo de cálculo
Supongamos que se mide la resistencia de un material y se obtiene la siguiente muestra de tamaño $n=5$: 
**$x = \{10, 12, 15, 11, 12\}$**

1.  **Calcular la media muestral ($\bar{x}$):**
    $$\bar{x} = \frac{10 + 12 + 15 + 11 + 12}{5} = \frac{60}{5} = 12$$

2.  **Calcular la suma de desviaciones al cuadrado ($\sum (x_i - \bar{x})^2$):**
    $$(10-12)^2 + (12-12)^2 + (15-12)^2 + (11-12)^2 + (12-12)^2$$
    $$(-2)^2 + (0)^2 + (3)^2 + (-1)^2 + (0)^2 = 4 + 0 + 9 + 1 + 0 = 14$$

3.  **Calcular la estimación puntual ($s^2$):**
    Se divide la suma entre $n-1$ (grados de libertad) para asegurar que el estimador sea **insesgado**.
    $$s^2 = \frac{14}{5 - 1} = \frac{14}{4} = 3.5$$

**Resultado:** La estimación puntual de la varianza poblacional $\sigma^2$ es **3.5**.

### ¿Por qué usar $n-1$ en lugar de $n$?
El texto explica que si se utiliza el divisor $n$, la cantidad resultante tendería a **subestimar** el valor real de $\sigma^2$. Al usar $n-1$, se corrige esta tendencia, convirtiendo a $S^2$ en un estimador centrado en el valor verdadero del parámetro.

Para estimar la varianza poblacional $\sigma^2$, se pueden utilizar los siguientes dos estadísticos:

### 1. Estimador Insesgado ($\hat{\sigma}^2$)
El estimador insesgado de la varianza poblacional es la **varianza muestral ($S^2$)** que utiliza el divisor $n-1$.
*   **Fórmula:** $S^2 = \frac{\sum (X_i - \bar{X})^2}{n-1}$.
*   **Justificación:** Se considera insesgado porque su valor esperado es exactamente igual a la varianza de la población ($E(S^2) = \sigma^2$). El uso del divisor $n-1$ compensa el hecho de que las observaciones muestrales tienden a estar más cerca de la media muestral que de la media poblacional verdadera.

### 2. Estimador Sesgado
Un estimador sesgado común es aquel que utiliza el divisor **$n$** en lugar de $n-1$.
*   **Fórmula:** $\hat{\sigma}^2 = \frac{\sum (X_i - \bar{X})^2}{n}$.
*   **Justificación:** Este estimador es sesgado porque tiende a **subestimar** sistemáticamente el valor real de $\sigma^2$, produciendo valores que son, en promedio, demasiado pequeños. Específicamente, su valor esperado es $\frac{n-1}{n}\sigma^2$, lo que genera un sesgo de $-\sigma^2/n$.

Para demostrar analíticamente que el estimador que utiliza el divisor $n$ para la varianza es sesgado, seguiremos el procedimiento detallado en las fuentes para relacionarlo con la varianza muestral insesgada ($S^2$).

### Demostración Analítica

1.  **Definición del estimador sesgado ($\hat{\sigma}^2$):** Se define como el promedio de las desviaciones al cuadrado utilizando $n$ como divisor:
    $$\hat{\sigma}^2 = \frac{\sum_{i=1}^{n} (X_i - \bar{X})^2}{n} \text{}$$

2.  **Relación con la varianza muestral ($S^2$):** Sabemos que la varianza muestral insesgada se define con el divisor $n-1$. Por lo tanto, el estimador sesgado se puede expresar como:
    $$\hat{\sigma}^2 = \frac{n-1}{n} S^2 \text{}$$

3.  **Aplicación del valor esperado:** Para verificar si es insesgado, calculamos su valor esperado:
    $$E(\hat{\sigma}^2) = E\left[ \frac{n-1}{n} S^2 \right] \text{}$$

4.  **Linealidad de la esperanza:** Sacamos la constante de la operación:
    $$E(\hat{\sigma}^2) = \frac{n-1}{n} E(S^2) \text{}$$

5.  **Sustitución de la varianza poblacional:** Dado que ya se ha demostrado que $S^2$ es un estimador insesgado de $\sigma^2$ ($E(S^2) = \sigma^2$), sustituimos:
    $$E(\hat{\sigma}^2) = \frac{n-1}{n} \sigma^2 \text{}$$

### Conclusión del Sesgo
El estimador es sesgado porque su valor esperado **no es igual** al parámetro $\sigma^2$. El cálculo del sesgo es:
$$\text{Sesgo} = E(\hat{\sigma}^2) - \sigma^2 = \frac{n-1}{n} \sigma^2 - \sigma^2 = -\frac{\sigma^2}{n} \text{}$$

Como el sesgo es negativo, este estimador tiene una tendencia sistemática a **subestimar** el valor real de la varianza poblacional, produciendo valores que son, en promedio, demasiado pequeños. Por esta razón, en estadística se prefiere utilizar el divisor $n-1$ para corregir esta desviación.

$$\sum(x_i - \bar{x})^2 = \sum x_i^2 - \frac{(\sum x_i)^2}{n}$$

Para demostrar analíticamente que el estimador $\hat{\sigma}^2 = \frac{\sum (X_i - \bar{X})^2}{n}$ es sesgado utilizando la identidad proporcionada, seguiremos el procedimiento de cálculo de valores esperados basado en las fuentes.

### Demostración Analítica

**1. Definición del estimador y aplicación de la identidad:**
Partimos de la fórmula del estimador sesgado y aplicamos la identidad de suma de cuadrados:
$$\hat{\sigma}^2 = \frac{1}{n} \sum_{i=1}^{n} (X_i - \bar{X})^2 = \frac{1}{n} \left[ \sum_{i=1}^{n} X_i^2 - \frac{(\sum X_i)^2}{n} \right]$$

**2. Aplicación del Valor Esperado:**
Para verificar si existe sesgo, aplicamos el operador de valor esperado $E[\cdot]$ a la expresión:
$$E[\hat{\sigma}^2] = \frac{1}{n} \left[ E\left( \sum X_i^2 \right) - \frac{1}{n} E\left( \left( \sum X_i \right)^2 \right) \right]$$

**3. Evaluación de los términos individuales:**
Utilizamos la propiedad fundamental $E(Y^2) = V(Y) + [E(Y)]^2$ para cada término:

*   **Para $\sum X_i^2$:** Como cada $X_i$ tiene media $\mu$ y varianza $\sigma^2$:
    $$E\left( \sum X_i^2 \right) = \sum E(X_i^2) = \sum (\sigma^2 + \mu^2) = n\sigma^2 + n\mu^2$$

*   **Para $(\sum X_i)^2$:** Dado que la varianza de la suma de variables independientes es la suma de sus varianzas ($n\sigma^2$) y el valor esperado de la suma es $n\mu$:
    $$E\left( \left( \sum X_i \right)^2 \right) = V\left( \sum X_i \right) + \left[ E\left( \sum X_i \right) \right]^2 = n\sigma^2 + (n\mu)^2 = n\sigma^2 + n^2\mu^2$$

**4. Sustitución y simplificación:**
Sustituimos estos resultados en la ecuación original:
$$E[\hat{\sigma}^2] = \frac{1}{n} \left[ (n\sigma^2 + n\mu^2) - \frac{n\sigma^2 + n^2\mu^2}{n} \right]$$
$$E[\hat{\sigma}^2] = \frac{1}{n} \left[ n\sigma^2 + n\mu^2 - (\sigma^2 + n\mu^2) \right]$$
$$E[\hat{\sigma}^2] = \frac{1}{n} [ (n-1)\sigma^2 ] = \frac{n-1}{n}\sigma^2$$

### Conclusión
El estimador es **sesgado** porque su valor esperado no es igual al parámetro $\sigma^2$. El sesgo se calcula como:
$$\text{Sesgo} = E[\hat{\sigma}^2] - \sigma^2 = \frac{n-1}{n}\sigma^2 - \sigma^2 = -\frac{\sigma^2}{n}$$

Como el sesgo es negativo, este estimador tiende sistemáticamente a **subestimar** la varianza poblacional. Por esta razón, el texto recomienda utilizar el divisor $n-1$, lo cual compensa esta diferencia y convierte al estimador en insesgado.

Para demostrar analíticamente que la varianza muestral $S^2 = \frac{\sum (X_i - \bar{X})^2}{n-1}$ es un estimador insesgado de la varianza poblacional $\sigma^2$, se debe verificar que $E(S^2) = \sigma^2$.

### Demostración Analítica

**1. Identidad fundamental:**
Se utiliza la propiedad de que para cualquier variable aleatoria $Y$, $V(Y) = E(Y^2) - [E(Y)]^2$, lo que implica que $E(Y^2) = V(Y) + [E(Y)]^2$.

**2. Expresión del estimador:**
Partimos de la fórmula de cálculo (fórmula de cómputo) para $S^2$:
$$S^2 = \frac{1}{n-1} \left[ \sum_{i=1}^{n} X_i^2 - \frac{1}{n} \left( \sum_{i=1}^{n} X_i \right)^2 \right]$$

**3. Aplicación del valor esperado:**
Aplicamos el operador $E(\cdot)$ a la expresión completa:
$$E(S^2) = \frac{1}{n-1} \left[ \sum_{i=1}^{n} E(X_i^2) - \frac{1}{n} E \left[ \left( \sum_{i=1}^{n} X_i \right)^2 \right] \right]$$

**4. Evaluación de los términos individuales:**
*   **Para el primer término:** Como cada $X_i$ tiene media $\mu$ y varianza $\sigma^2$, entonces $E(X_i^2) = \sigma^2 + \mu^2$. Al sumarlos $n$ veces:
    $$\sum E(X_i^2) = n(\sigma^2 + \mu^2)$$
*   **Para el segundo término:** Definimos $Y = \sum X_i$. Sabemos que $V(\sum X_i) = n\sigma^2$ y $E(\sum X_i) = n\mu$. Aplicando la propiedad del paso 1:
    $$E \left[ \left( \sum X_i \right)^2 \right] = V \left( \sum X_i \right) + \left[ E \left( \sum X_i \right) \right]^2 = n\sigma^2 + (n\mu)^2$$

**5. Sustitución y simplificación:**
Sustituimos ambos resultados en la ecuación de $E(S^2)$:
$$E(S^2) = \frac{1}{n-1} \left[ n\sigma^2 + n\mu^2 - \frac{1}{n} (n\sigma^2 + n^2\mu^2) \right]$$
$$E(S^2) = \frac{1}{n-1} \left[ n\sigma^2 + n\mu^2 - \sigma^2 - n\mu^2 \right]$$
$$E(S^2) = \frac{1}{n-1} [ n\sigma^2 - \sigma^2 ] = \frac{n-1}{n-1} \sigma^2$$

**Resultado final:**
$$E(S^2) = \sigma^2$$

### Conclusión
Puesto que el valor esperado del estimador $S^2$ es exactamente igual al parámetro poblacional $\sigma^2$, se concluye que **la varianza muestral calculada con el divisor $n-1$ es un estimador insesgado**. El uso de $n-1$ compensa la tendencia de los datos muestrales a estar más cerca de su propia media ($\bar{X}$) que de la media poblacional verdadera ($\mu$).

## Minimum variance unbiased estimator

El **Estimador Insesgado con Varianza Mínima (EIVM)** de un parámetro $\theta$ es aquel estadístico que, entre todos los estimadores que son insesgados para ese parámetro, posee la varianza más pequeña. Debido a su baja variabilidad, el EIVM es el estimador que tiene más probabilidades de producir una estimación cercana al valor verdadero del parámetro poblacional.

**Ejemplo:**
Si se extrae una muestra aleatoria de una **distribución normal** con media $\mu$ y desviación estándar $\sigma$, la media muestral $\bar{X}$ es el EIVM para estimar la media poblacional $\mu$. Aunque existen otros estimadores insesgados para este caso (como la mediana o la media recortada), la media muestral se prefiere porque es la que ofrece mayor precisión al tener la varianza mínima.

Si tengo $\hat{\theta}_1$ y $\hat{\theta}_2$ estimadores insesgados de $\theta$, el "mejor" es el de menor varianza.

Es correcto. Según el **Principio de estimación insesgada con varianza mínima**, cuando se debe elegir entre varios estimadores insesgados para un parámetro $\theta$, se selecciona aquel que posea la varianza más pequeña. 

Esta elección se justifica porque un estimador con menor variabilidad es el que tiene más probabilidades de producir un valor numérico cercano al valor verdadero del parámetro poblacional. Al estadístico resultante de este criterio se le conoce formalmente como **Estimador Insesgado con Varianza Mínima (EIVM)**.

El **método de momentos** es una técnica constructiva utilizada en estadística para obtener estimadores puntuales de parámetros poblacionales desconocidos. Su principio fundamental consiste en igualar las características observadas en una muestra con sus contrapartes teóricas de la población y resolver las ecuaciones resultantes para hallar los parámetros de interés.

A continuación se detallan los componentes analíticos de este método según el texto de estudio:

## Momentos poblacionales

### Definición Analítica
El **$k$-ésimo momento de la población** (o de la distribución) se define como el valor esperado de la variable aleatoria elevada a la potencia $k$:
$$E(X^k)$$
donde $k = 1, 2, 3, \dots$.

### Explicación
Los momentos poblacionales representan valores teóricos que describen la forma y características de una distribución. Por lo general, estos momentos son funciones de los parámetros desconocidos de la población ($\theta_1, \theta_2, \dots, \theta_m$).
*   **Ejemplo:** El primer momento poblacional ($k=1$) es simplemente la media de la población, denotada como $E(X) = \mu$. El segundo momento poblacional ($k=2$) es $E(X^2)$.

---

## Momentos muestrales

### Definición Analítica
El **$k$-ésimo momento muestral** se calcula directamente a partir de las observaciones de una muestra aleatoria de tamaño $n$ ($X_1, \dots, X_n$) mediante la siguiente fórmula:
$$\frac{1}{n} \sum_{i=1}^{n} X_i^k$$
donde $k = 1, 2, 3, \dots$.

### Explicación
Los momentos muestrales son las "versiones empíricas" de los momentos poblacionales, obtenidos a partir de los datos recolectados en un experimento.
*   **Ejemplo:** El primer momento muestral ($k=1$) es la media muestral, expresada como $\frac{1}{n} \sum X_i$ o $\bar{X}$. El segundo momento muestral ($k=2$) es el promedio de los cuadrados de las observaciones, $\frac{1}{n} \sum X_i^2$.

---

## Procedimiento del método
Para obtener los **estimadores de momentos** ($\hat{\theta}_1, \dots, \hat{\theta}_m$) de $m$ parámetros desconocidos, el procedimiento analítico es el siguiente:

1.  Se igualan los primeros $m$ momentos poblacionales con los primeros $m$ momentos muestrales:
    *   $E(X) = \frac{1}{n} \sum X_i$
    *   $E(X^2) = \frac{1}{n} \sum X_i^2$
    *   ... (así sucesivamente hasta el momento $m$).
2.  Se resuelve el sistema de ecuaciones resultante para despejar los parámetros $\theta_i$.

**Nota sobre la utilidad:** Aunque este método es intuitivo y fácil de calcular para parámetros simples como la media $\mu$ (donde el estimador de momento es directamente $\bar{X}$), en distribuciones más complejas como la **Gama** o la **Binomial Negativa**, puede requerir la resolución de sistemas de ecuaciones más elaborados.

Para desarrollar un ejemplo analítico del **método de momentos** con dos parámetros ($m=2$), utilizaremos el caso de la **distribución Gama**, que es el ejemplo más detallado en las fuentes para este nivel de complejidad.

### 1. Definición del Método (m=2)
El método de momentos consiste en igualar los primeros $m$ momentos de la población con los primeros $m$ momentos de la muestra. Para dos parámetros ($m=2$), las ecuaciones fundamentales son:
*   **Primer momento ($k=1$):** $E(X) = \bar{X}$
*   **Segundo momento ($k=2$):** $E(X^2) = \frac{1}{n} \sum X_i^2$.

---

### 2. Aplicación a la Distribución Gama
Supongamos una muestra aleatoria $X_1, \dots, X_n$ proveniente de una distribución Gama con parámetros $\alpha$ (forma) y $\beta$ (escala).

#### A. Momentos Poblacionales
Basándonos en las propiedades de la distribución Gama:
1.  **Media poblacional:** $E(X) = \alpha\beta$.
2.  **Segundo momento poblacional:** Se sabe que $E(X^2) = V(X) + [E(X)]^2$. Para la distribución Gama, la varianza es $V(X) = \alpha\beta^2$. Por lo tanto:
    $$E(X^2) = \alpha\beta^2 + (\alpha\beta)^2 = \alpha\beta^2 + \alpha^2\beta^2 = \alpha(\alpha + 1)\beta^2 \text{}$$

#### B. Momentos Muestrales
1.  **Primer momento muestral:** $\bar{X} = \frac{1}{n} \sum X_i$.
2.  **Segundo momento muestral:** $\frac{1}{n} \sum X_i^2$.

---

### 3. Desarrollo Analítico (Resolución del Sistema)
Igualamos los momentos poblacionales con los muestrales para formar el sistema de dos ecuaciones con dos incógnitas ($\alpha$ y $\beta$):

1.  $\bar{X} = \alpha\beta$
2.  $\frac{1}{n} \sum X_i^2 = \alpha(\alpha + 1)\beta^2$.

**Paso 1: Despejar $\beta$ de la primera ecuación.**
$$\beta = \frac{\bar{X}}{\alpha}$$

**Paso 2: Sustituir $\beta$ en la segunda ecuación.**
$$\frac{1}{n} \sum X_i^2 = \alpha(\alpha + 1) \left( \frac{\bar{X}}{\alpha} \right)^2$$
$$\frac{1}{n} \sum X_i^2 = \alpha(\alpha + 1) \frac{\bar{X}^2}{\alpha^2}$$
$$\frac{1}{n} \sum X_i^2 = \frac{\alpha + 1}{\alpha} \bar{X}^2$$

**Paso 3: Resolver para $\alpha$.**
$$\frac{\frac{1}{n} \sum X_i^2}{\bar{X}^2} = \frac{\alpha + 1}{\alpha} = 1 + \frac{1}{\alpha}$$
$$\frac{1}{\alpha} = \frac{\frac{1}{n} \sum X_i^2}{\bar{X}^2} - 1 = \frac{\frac{1}{n} \sum X_i^2 - \bar{X}^2}{\bar{X}^2}$$
Invirtiendo la fracción, obtenemos el estimador de momento para $\alpha$ ($\hat{\alpha}$):
$$\hat{\alpha} = \frac{\bar{X}^2}{\frac{1}{n} \sum X_i^2 - \bar{X}^2} \text{}$$

**Paso 4: Resolver para $\beta$.**
Sustituimos $\hat{\alpha}$ en la relación $\beta = \bar{X}/\alpha$:
$$\hat{\beta} = \frac{\bar{X}}{\hat{\alpha}} = \frac{\bar{X}}{\frac{\bar{X}^2}{\frac{1}{n} \sum X_i^2 - \bar{X}^2}} = \frac{\frac{1}{n} \sum X_i^2 - \bar{X}^2}{\bar{X}} \text{}$$

### Conclusión
Los estimadores de momentos para una distribución Gama ($m=2$) son estadísticos que utilizan la media muestral y el promedio de los cuadrados de las observaciones para realizar una "mejor conjetura" de los parámetros poblacionales. Analíticamente, estos estimadores capturan la relación entre el centro y la dispersión de los datos para definir la forma de la distribución.

## Ejemplo 5

$$X\sim N(x;\mu,\sigma^2)$$

Para desarrollar el ejemplo analítico de estimación para una distribución normal $X \sim N(\mu, \sigma^2)$, utilizaremos el **método de momentos**, el cual consiste en igualar los momentos teóricos de la población con los momentos observados en la muestra.

Dado que la distribución normal tiene dos parámetros desconocidos ($\theta_1 = \mu$ y $\theta_2 = \sigma^2$), debemos plantear y resolver un sistema de dos ecuaciones ($m=2$).

### 1. Identificación de los Momentos

**A. Momentos Poblacionales (Teóricos):**
Basándonos en las propiedades de la distribución normal:
*   **Primer momento ($k=1$):** Es el valor esperado de la variable, $E(X) = \mu$.
*   **Segundo momento ($k=2$):** Es el valor esperado del cuadrado de la variable. Utilizando la relación $V(X) = E(X^2) - [E(X)]^2$, despejamos $E(X^2)$:
    $$E(X^2) = V(X) + [E(X)]^2 = \sigma^2 + \mu^2$$

**B. Momentos Muestrales (Empíricos):**
Se calculan directamente de la muestra de tamaño $n$:
*   **Primer momento muestral:** $M_1 = \frac{1}{n} \sum_{i=1}^{n} X_i = \bar{X}$.
*   **Segundo momento muestral:** $M_2 = \frac{1}{n} \sum_{i=1}^{n} X_i^2$.

---

### 2. Sistema de Ecuaciones
Igualamos los momentos poblacionales a los muestrales para obtener los estimadores ($\hat{\mu}$ y $\hat{\sigma}^2$):

1.  $\mu = \bar{X}$
2.  $\sigma^2 + \mu^2 = \frac{1}{n} \sum X_i^2$

---

### 3. Resolución Analítica

**Paso 1: Estimador de la media ($\hat{\mu}$)**
De la primera ecuación se obtiene directamente:
$$\hat{\mu} = \bar{X}$$
Este es el estimador de momentos para la media poblacional.

**Paso 2: Estimador de la varianza ($\hat{\sigma}^2$)**
Sustituimos $\mu$ por su estimador $\bar{X}$ en la segunda ecuación:
$$\hat{\sigma}^2 + \bar{X}^2 = \frac{1}{n} \sum X_i^2$$
Despejamos $\hat{\sigma}^2$:
$$\hat{\sigma}^2 = \frac{1}{n} \sum X_i^2 - \bar{X}^2$$

**Paso 3: Simplificación elegante**
Utilizando la identidad algebraica de la suma de cuadrados, $\sum (X_i - \bar{X})^2 = \sum X_i^2 - n\bar{X}^2$, podemos reescribir el estimador de la siguiente manera:
$$\hat{\sigma}^2 = \frac{\sum X_i^2 - n\bar{X}^2}{n} = \frac{\sum_{i=1}^{n} (X_i - \bar{X})^2}{n}$$

---

### 4. Análisis de los Estimadores Obtenidos

*   **Insesgamiento de $\hat{\mu}$:** Como se demostró previamente, $E(\bar{X}) = \mu$, por lo que la media muestral es un **estimador insesgado**. Además, para una población normal, $\bar{X}$ es el Estimador Insesgado de Varianza Mínima (EIVM).
*   **Sesgo de $\hat{\sigma}^2$:** El método de momentos para la distribución normal produce un estimador que utiliza el divisor $n$. Analíticamente, este estimador es **sesgado**, ya que su valor esperado es $\frac{n-1}{n}\sigma^2$, lo que significa que tiende a subestimar la varianza real de la población. Por esta razón, se suele preferir el uso de la varianza muestral $S^2$ (con divisor $n-1$), que es el estimador corregido e insesgado.

Para la próxima clase se estudiará maximum likelihood